on: push
name: Example Workflow
jobs:
  runNpmEslint:
    name: Run NPM eslint
    runs-on: ${{ matrix.os }}
    strategy:
        matrix: 
            os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
        - uses: actions/checkout@v2
        - name: Setup node
          uses: actions/setup-node@v1
          with:
            node-version: '8'
        - run: npm install
        - run: npm install bower polymer-cli 
        - run: bower install
        - run: npm run check
        - run: npm run lint
        - run: wct
